### PR TITLE
Update License text in README

### PR DESCRIPTION
**Pull request by white-gecko**
@vitaB gave his ok already:
> Hallo Konrad,
> ja, GPL find ich gut.
> Viele Grüße
> Viktor

@oliverskawronek as well:

> Hallo Konrad,
> 
> ja, ihr könnte nach Belieben (auch für die Zukunft) die Lizenz umstellen.
>
> […]
>
> Ciao Oliver

### CODE REVIEW

**Review by k00ni — CHANGES_REQUESTED** [review]
I would like to change to copyright-list in one of two ways:

- Either use "Copyright (C) by Konrad Abicht and Natanel Arndt and contributors" 
(with or without URL afterwards)

- Or use "Copyright (C) by SaftIng organization and contributors".

I prefer the first one.

**Review by k00ni — APPROVED** [review]

**Comment by k00ni** [comment]
Sorry, i miss-clicked so i re-requested a review.

**Review by k00ni — CHANGES_REQUESTED** [review]
I would like to change to copyright-list in one of two ways:

Either use "Copyright (C) by Konrad Abicht and Natanel Arndt and contributors"
(with or without URL afterwards)

Or use "Copyright (C) by SaftIng organization and contributors".

I prefer the first one.

**Review by pfrischmuth — CHANGES_REQUESTED** [review]
I agree with Konrad, that not every contributor should be listed explicitly... Otherwise you have to change the file every time someone new contributes.

**Comment by white-gecko** [comment]
But since everybody holds parts of the copyright, I think it is ok to list all of the names.
Furthermore it would be good, if every contributor adds here/his name we also have an up to date list of contributors, which might need to be asked in order to do changes like this one.

**Review by k00ni — APPROVED** [review]
As discussed. :+1:

**Review by pfrischmuth — APPROVED** [review]
LGTM

**Pull request merged**
